### ISSUE TITLE
It is better not to erase the source notation.

### ISSUE THREAD

**Issue by zrma** [namonak/HackerRank#1]
https://github.com/namonak/HackerRank/blob/8f0cc20e9036297930e70d37e03263c483650398/.gitignore#L1

You should add gitignore source notation - https://gitignore.io/api/c,windows.

**Comment by namonak** [comment]
Sorry, I did not recognize the source notation.
I added source notation to .gitignore with the hash code below.
- b6e39ff35baf2eb34cd06eadc7df690a2cb24ecd

Thanks for your advice!
