### ISSUE TITLE
import _

### ISSUE THREAD

**Issue by zrma** [namonak/HackerRank#3]
https://github.com/namonak/HackerRank/blob/e03c020b900c167168364c289ad3ba6b9d217457/30_Days_of_Code/Day1-Data_Types.go#L12

`import _ "strconv"`

**Comment by namonak** [comment]
사용하지 않는 strconv 패키지를 처리하였습니다.
- da53a1eab32df15106ba31d329146c394534cf1a
- Reference : http://pyrasis.com/book/GoForTheReallyImpatient/Unit07/02
