### ISSUE TITLE
네이밍 컨벤션

### ISSUE THREAD

**Issue by zrma** [namonak/HackerRank#4]
https://github.com/namonak/HackerRank/blob/e03c020b900c167168364c289ad3ba6b9d217457/30_Days_of_Code/Day1-Data_Types.go#L21

`_`는 보통 사용하지 않는 듯...

**Comment by namonak** [comment]
네이밍 컨벤션 자료 참고해서 수정 후 커밋했습니다. 근데 제대로 했는지는 모르겠네요 ㅎㅎ
- 0acf76ad1e1c6e0c2ee0fdabf6f38a5eed494acb
- Reference : https://www.slideshare.net/devcatpublications/ndc2018

**Comment by zrma** [comment]
@namonak 어느 시대적 유물입니까! (탕탕).  

보통 변수명에 자료형 안 넣는 듯.
