### ISSUE TITLE
Variables name.

### ISSUE THREAD

**Issue by zrma** [namonak/HackerRank#7]
https://github.com/namonak/HackerRank/blob/2114f257b9572a73f7bc08685124f617d4253ff6/30_Days_of_Code/Day4-Class_vs_Instance.go#L38

@namonak 변수명 T를 유의미한 소문자로...

go언어에서 prefix의 대소문자는 문법적 의미를 지니고 있기 때문에 조심하는게 좋음.

**Comment by namonak** [comment]
@zrma 코멘트 해주신 대로 변수명 T를 testcase로 변경하였습니다!
- f8d13950d63a7a20bee9d8421bd920f4bb851684
