### ISSUE TITLE
예외 처리

### ISSUE THREAD

**Issue by zrma** [namonak/HackerRank#8]
https://github.com/namonak/HackerRank/blob/0649b56fcac3ead04c08609c222033f2803c4185/30_Days_of_Code/Day0-Hello_World.go#L14

```go
log.Fatalf("%v", err)
```
정도면 무난하지 않을까?

**Comment by namonak** [comment]
네, 해당 예러로그 추가하였습니다~
 - 57307bfa3ce4ee6c5515fe40e2a45ef25dc71a51
 - Reference : http://golang.site/go/article/19-Go-%EC%97%90%EB%9F%AC%EC%B2%98%EB%A6%AC
