### ISSUE TITLE
Use for loop

### ISSUE THREAD

**Issue by zrma** [namonak/HackerRank#9]
https://github.com/namonak/HackerRank/blob/fe403320d0a62a122842378bb11f60abe591166e/C/DigitFrequency/digit_frequency.c#L16

```c
for(i = 0; i < MAX_INPUT_LENGTH && inputArr[i] != '\0'; ++i) {
    if(inputArr[i] >= ASCII_CODE_ZERO && inputArr[i] <= ASCII_CODE_NINE) {
        outputArr[inputArr[i] - ASCII_CODE_ZERO]++;
    }
}
```

**Comment by namonak** [comment]
오... 위에 코드가 훨씬 간결해 보이네요! 아래 커밋에 적용해 두었습니다.
- c3503403448c3469a85607c869ef1c9b95914c01
